import Foundation

// Register each area's tests, then run. Later tasks append their <area>Tests() call here.
sanityTests()
macNotchAppTests()
notchBrandTests()
notchStateMachineTests()
notchWindowTests()
settingsStoreTests()
energyRefreshPolicyTests()
moduleRegistryTests()
screenLocatorTests()
systemSampleTests()
mediaControllerTests()
calendarFormatTests()
calendarModuleTests()
shelfStoreTests()
settingsLogicTests()
codeModuleCoreTests()
codingIntelTests()
stocksSelectionTests()
screenTimeTrackerTests()
timerSchedulerTests()

exit(Int32(TestRunner.shared.runAll()))
