import Foundation

// Register each area's tests, then run. Later tasks append their <area>Tests() call here.
sanityTests()
macNotchAppTests()
notchBrandTests()
notchStateMachineTests()
notchWindowTests()
settingsStoreTests()
appDataMigratorTests()
appDataPersistenceTests()
energyRefreshPolicyTests()
moduleRegistryTests()
screenLocatorTests()
systemSampleTests()
mediaControllerTests()
calendarFormatTests()
calendarModuleTests()
shelfStoreTests()
settingsLogicTests()
notchAppearanceTests()
notchThemeTests()
customizeModuleTests()
codeModuleCoreTests()
codingIntelTests()
stocksSelectionTests()
screenTimeTrackerTests()
timerSchedulerTests()
onboardingStateTests()
featureFlagsTests()
workspaceProfileTests()
commandPaletteTests()

exit(Int32(TestRunner.shared.runAll()))
